### ISSUE TITLE
Gallery problem

### ISSUE THREAD

**Issue by djole7401** [meglio/WooCommerce-Measurement-Price-Calculator#6]
Greeting. After activation of this plugin there is a change in the gallery view.
Befor this plugin:
http://prntscr.com/r7ks1q
After activating:
http://prntscr.com/r7kts1
What could have caused it?
Thank you!

**Comment by FFritzy** [comment]
Same problem here?
Jel si uspeo da resis ovo?

**Comment by djole7401** [comment]
Yes. I change plugin! :)

**Comment by FFritzy** [comment]
Javio sam ti se na insta. Pogledaj messeage requestove

**Comment by djole7401** [comment]
Nisam dobio requestove. Pošalji na mail. Ovo korisničko pa google.
